services:
  - type: web
    name: leaty-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
